### ISSUE TITLE
Kubernetes 概述

### ISSUE THREAD

**Issue by phymo** [phymooc/learn-kubernetes#1]
Kubernetes 是 Google 团队发起的开源项目，它的目标是管理跨多个主机的容器，提供基本的部署，维护以及应用伸缩，主要实现语言为 Go 语言。Kubernetes 是：
易学：轻量级，简单，容易理解
便携：支持公有云，私有云，混合云，以及多种云平台
可拓展：模块化，可插拔，支持钩子，可任意组合
自修复：自动重调度，自动重启，自动复制
Kubernetes 构建于 Google 数十年经验，一大半来源于 Google 生产环境规模的经验。结合了社区最佳的想法和实践。
在分布式系统中，部署，调度，伸缩一直是最为重要的也最为基础的功能。Kubernetes 就是希望解决这一序列问题的。

### 命令：
`kubectl apply -f yamlFile`  pod/service/deploy/replicaset/configMap 等yaml文件 都可以直接运行
`kubectl get pod/svc/deploy/replica/cm` 获取列表
`kubectl describe pod/svc/deploy/replica/cm name` 查看信息，相当于docker inspect
`get logs pod container` 查看日志
`kubectl exec -it pod -c container command` -c 即 --container

**Comment by phymo** [comment]
![image](https://user-images.githubusercontent.com/7558104/115372551-9bf11d00-a1fd-11eb-82e2-eea91ba0aaaf.png)

![image](https://user-images.githubusercontent.com/7558104/115372520-93004b80-a1fd-11eb-8677-9f0fe8e80222.png)

**Comment by phymo** [comment]
# 概念和结构

计算机集群（英语：computer cluster）是一组松散或紧密连接在一起工作的计算机。由于这些计算机协同工作，在许多方面它们可以被视为单个系统。与网格计算机不同，计算机集群将每个节点设置为执行相同的任务，由软件控制和调度。

真正的生产型应用会涉及多个容器。这些容器必须跨多个服务器主机进行部署。容器安全性需要多层部署，因此可能会比较复杂。但 Kubernetes 有助于解决这一问题。Kubernetes 可以提供所需的编排和管理功能，以便您针对这些工作负载大规模部署容器。
![image](https://user-images.githubusercontent.com/7558104/120148070-3ccdf180-c21a-11eb-91cc-08a9325a4792.png)

Master Node:
![image](https://user-images.githubusercontent.com/7558104/120148097-46eff000-c21a-11eb-91dc-ab98ee8d09b2.png)
> etcd: 集群状态存储
> api server: 接口， 接受client 命令，向kubelet 发送指令等
> scheduler: 集群资源调度： 如新的pod 在哪台主机启动
> Controller Manager:  最终一致调度策略

Work Node:
![image](https://user-images.githubusercontent.com/7558104/120148134-52431b80-c21a-11eb-977b-22c60b8c7925.png)
> kubelet: 资源管理者 启动关闭pod
> container run time: 相当于 docker engine
> kube-proxy: 管理 service 网络
Summary
![image](https://user-images.githubusercontent.com/7558104/120148166-5ec77400-c21a-11eb-8736-187ce4110a6d.png)

**Comment by phymo** [comment]
# Pod （虚拟机抽象）
![image](https://user-images.githubusercontent.com/7558104/120148248-81f22380-c21a-11eb-917b-1b834071fe6b.png)
> Pod 是对容器的包装，通常一个pod只运行一个容器，如果多个容器关系紧密，也可以运行在同一个pod上
![image](https://user-images.githubusercontent.com/7558104/120148276-8cacb880-c21a-11eb-8f64-45123236362b.png)

 pod yaml 文件示例：
``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - name: ubuntu
    image: ubuntu:trusty
    command: ["echo"]
    args: ["Hello World"]
```
> 使用 `kubectl apply -f file` 可以运行 yaml 文件生成并启动pod

**Comment by phymo** [comment]
# Service
暴露服务 相当于 nginx，可以实现反向代理和load balance，

三种类型：
NodePort 对外暴露服务
Loadbalancer 对外暴露服务（公有云）
ClusteIP  内部服务访问， 
![image](https://user-images.githubusercontent.com/7558104/120148470-dd241600-c21a-11eb-98a3-7a60b48aea31.png)

service yaml 示例：
``` yaml
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-example
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      targetPort: 80
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: nginx
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer
```
> port: 暴露给外网的端口
> targetPort: 指向Pod 的目标端口， 缺省值与 port相同

selector & label: 确定将请求转发给哪个服务， 可以实现蓝绿发布
![image](https://user-images.githubusercontent.com/7558104/120148510-edd48c00-c21a-11eb-864a-c7824828644a.png)

**Comment by phymo** [comment]
# ReplicaSet
高可用 Self-healing

```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  # Unique key of the ReplicaSet instance
  name: replicaset-example
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      # Run the nginx image
      - name: nginx
        image: nginx:1.14
```
> 这里面的 template 内部的信息 就是要启动的pod 信息

**Comment by phymo** [comment]
# Deployment 
默认是滚动发布 RollingUpdate
![image](https://user-images.githubusercontent.com/7558104/120148663-2c6a4680-c21b-11eb-81cb-eab1d0d4dbab.png)
![image](https://user-images.githubusercontent.com/7558104/120148673-32602780-c21b-11eb-8081-7f38a586fe8d.png)


``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: deployment-example
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nginx
    spec:
      containers:
      - name: nginx
        # Run this image
        image: nginx:1.14
```
> template 里面的内容是pod

**Comment by phymo** [comment]
# ConfigMap 
In Kubernetes, a ConfigMap is simply an object for storing configuration data. Other things, like pods, can access the data in a ConfigMap.
k8s 配置抽象
![image](https://user-images.githubusercontent.com/7558104/120148936-908d0a80-c21b-11eb-8b99-71372659a74c.png)

yaml 文件 参考 NCC 项目：

1. 以环境变量的方式加载 configMap 
``` yaml
envFrom:
       -confgMapRef:
             name: configmapName
```
> 验证ENV 注入成功： 进入容器 `printenv`
> configMap 更新之后，pod里面的ENV 并不会自动热更新，需要重新启动pod
2. 以Volume的方式绑定 ConfigMap, 支持热更新。
