### ISSUE TITLE
Helm charts

### ISSUE THREAD

**Issue by phymo** [phymooc/learn-kubernetes#2]
### The Purpose of Helm
Helm is a tool for managing Kubernetes packages called charts. Helm can do the following:

- Create new charts from scratch
- Package charts into chart archive (tgz) files
- Interact with chart repositories where charts are stored
- Install and uninstall charts into an existing Kubernetes cluster
- Manage the release cycle of charts that have been installed with Helm

For Helm, there are three important concepts:

- The chart is a bundle of information necessary to create an instance of a Kubernetes application.
- The config contains configuration information that can be merged into a packaged chart to create a releasable object.
- A release is a running instance of a chart, combined with a specific config.

**Comment by phymo** [comment]
yaml 模板语法：使用go语法
`a:=b` go： Short variable declarations
`{{-`语法去除模板内容左侧的所有空白符号, 使用`-}}`去除模板内容右侧的所有空白的符号.

**Comment by phymo** [comment]
range 关键字来遍历数据 : `{{ range array }}....{{end}}`
管道符：`|`前一个命令的输出结果是作为下一个命令的最后一个参数，最终命令的输出结果就是这个管道的结果

**Comment by phymo** [comment]
Files: This provides access to all non-special files in a chart. While you cannot use it to access templates, you can use it to access other files in the chart. See the section Accessing Files for more. 
- Files.Glob is a function that returns a list of files whose names match the given shell glob pattern.
- Files.Get is a function for getting a file by name

> Files: A map-like object containing all non-special files in the chart. This will not give you access to templates, but will give you access to additional files that are present (unless they are excluded using .helmignore). Files can be accessed using {{ index .Files "file.name" }} or using the {{.Files.Get name }} function. You can also access the contents of the file as []byte using {{ .Files.GetBytes }}

**Comment by phymo** [comment]
`base`:  Return the last element of a path. eg. `base "foo/bar/baz"` return baz;

**Comment by phymo** [comment]
`{{- range $path, $bytes := .Files.Glob (printf "configs/%s/*" (required "profile must be set" .Values.profile)) -}}` : 返回configs/beta/下的所有文件的路径和大小， 并遍历

**Comment by phymo** [comment]
- Chart.yaml: Various metadata such as chart name and version
- values.yaml: Basic values ​​of various variables used in the chart
- templates/: chart template of resources to install on kubernetes cluster
  - deployment.yaml: A basic manifest for creating a Kubernetes deployment
  - service.yaml: A basic manifest for creating a service endpoint for your deployment
  - _helpers.tpl: A place to put template helpers that you can re-use throughout the chart

**Comment by phymo** [comment]
- In Kubernetes, a ConfigMap is simply an object for storing configuration data. Other things, like pods, can access the data in a ConfigMap.

**Comment by phymo** [comment]
Values Object: This object provides access to values passed into the chart.  from: 
- The values.yaml file in the chart
- If this is a subchart, the values.yaml file of a parent chart
- A values file if passed into helm install or helm upgrade with the -f flag (helm install -f myvals.yaml ./mychart)
- Individual parameters passed with --set (such as helm install --set foo=bar ./mychart)

**Comment by phymo** [comment]
The `|-` marker in YAML takes a multi-line string. This can be a useful technique for embedding big blocks of data inside of your manifests, as exemplified here. 
> 在ncc 的 configmap.yaml里面 load nginx.conf 里面的内容
```
{{- base $path | nindent 2 }}: |-
  {{- required (printf "config file does not exists (%s)" $path) ($root.Files.Get $path) | nindent 4 }}
```

**Comment by phymo** [comment]
_helpers.tpl: 
files whose name begins with an underscore (_) are assumed to not have a manifest inside. These files are not rendered to Kubernetes object definitions, but are available everywhere within other chart templates for use.

**Comment by phymo** [comment]
define template
include template

**Comment by phymo** [comment]
``` YAML
apiVersion: chart API 版本 (必须)
name: chart 名 (必须)
version: SemVer 2版本 (必须)
kubeVersion: 兼容的 Kubernetes 版本 (可选)
description: 一句话描述 (可选)
type: chart 类型 (可选)
keywords:
  - 当前项目关键字集合 (可选)
home: 当前项目的 URL (可选)
sources:
  - 当前项目源码 URL (可选)
dependencies: # chart 依赖列表 (可选)
  - name: chart 名称 (nginx)
    version: chart 版本 ("1.2.3")
    repository: 仓库地址 ("https://example.com/charts")
maintainers: # (可选)
  - name: 维护者名字 (对每个 maintainer 是必须的)
    email: 维护者的 email (可选)
    url: 维护者 URL (可选)
icon: chart 的 SVG 或者 PNG 图标 URL (可选).
appVersion: 包含的应用程序版本 (可选). 不需要 SemVer 版本
deprecated: chart 是否已被弃用 (可选, boolean)
```
